---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: cicd-dp
spec: 
  minReadySeconds: 5
  replicas: 4
  selector:
    matchLabels: SPC
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata: 
      name: ecrimage
      labels: SPCAPP
    spec:
      containers:
        - image: 688567298785.dkr.ecr.us-west-2.amazonaws.com/dev/cicdrepo:latest
          ports:
            - containerPort: 8080         
---
apiVersion: v1
kind: Service
metadata:
  name: svc-dp
spec: 
  type: LoadBalancer
  selector: SPCAPP
  ports:
    - protocol: "TCP" 
      port: 8080
      targetPort: 8080          